name: gatelite-local

services:
  traefik:
    image: traefik:v3.5
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --metrics.prometheus=true
      - --metrics.prometheus.addentrypointslabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addserviceslabels=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/dynamic
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=gatelite_proxy
      - --log.level=INFO
    ports:
      - "18080:80"
      - "18443:443"
      - "18081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./runtime/traefik:/dynamic:ro
      - ./runtime/certs:/certs:ro
    networks:
      - gatelite_proxy

  whoami:
    image: traefik/whoami:v1.11.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.docker-whoami.rule=Host(`docker.localhost`)
      - traefik.http.routers.docker-whoami.entrypoints=web
      - traefik.http.services.docker-whoami.loadbalancer.server.port=80
    networks:
      - gatelite_proxy

networks:
  gatelite_proxy:
    name: gatelite_proxy
